apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sidecars
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: sidecars
    name: sidecars
  spec:
    replicas: 1
    selector:
      app: sidecars
      deploymentconfig: sidecars
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: sidecars
          deploymentconfig: sidecars
      spec:
        containers:
        - image: 172.30.1.1:5000/${PROJ}/container1:latest
          imagePullPolicy: Always
          name: container1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: 172.30.1.1:5000/${PROJ}/container2:latest
          imagePullPolicy: Always
          name: container2
          ports:
          - containerPort: 2000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - container1
        from:
          kind: ImageStreamTag
          name: container1:latest
      type: ImageChange
parameters:
- description: Project 
  name: PROJ
  required: true
