apiVersion: v1
kind: Service
metadata:
  labels:
    app: netcat-echo
  name: netcat-echo-external
spec:
  ports:
  - port: 2000
    targetPort: 2000
    nodePort: 30000
  selector:
    deploymentconfig: netcat-echo 
  sessionAffinity: None
  type: "NodePort"
