#!/bin/sh

set -ex

echo "---> Preparing source..."

# Create a directory for the source code.
mkdir -p /tmp/myapp

# Note that a more sophistaicated way of doing this would be to place the code in a location dedicated for the runtime. 

# Copy the 'source code' to where the 'cat' runtime will expect it to be
cp -Rf /tmp/src/src/. /tmp/myapp

