#!/bin/sh

echo "\
This is a simple s2i builder image example which runs the very simple 'cat runtime'.

Example: 
oc new-app s2i-simple-builder~https://github.com/sjbylo/ocp-topics --context-dir s2i-simple-builder/myapp --name myapp
"

